type: svm
model:
  C: 1.0
  kernel: linear
  gamma: scale
  sfreq: 250
  n_components: 4
  bands:
    - [4, 8]
    - [8, 12]
    - [12, 16]
    - [16, 20]
    - [20, 24]
    - [24, 28]
    - [28, 32]
    - [32, 36]
    - [36, 40]
train:
  batch_size: 0
  epochs: 1
  num_workers: 0
evaluation:
  best_metric: kappa
  best_direction: max
