name: bci2a
raw_dir: ./data/raw/BCICIV_2a_gdf
true_labels_dir: ./data/raw/true_labels
require_eval_labels: true
processed_dir: ./artifacts/preprocessed/bci2a
index_path: ./artifacts/preprocessed/bci2a/index.csv
subjects: [1,2,3,4,5,6,7,8,9]
channels:
  - Fz
  - FC3
  - FC1
  - FCz
  - FC2
  - FC4
  - C5
  - C3
  - C1
  - Cz
  - C2
  - C4
  - C6
  - CP3
  - CP1
  - CPz
  - CP2
  - CP4
  - P1
  - Pz
  - P2
  - POz
sfreq: 250
class_map:
  "769": 0
  "770": 1
  "771": 2
  "772": 3
class_names: [left_hand, right_hand, feet, tongue]
window:
  tmin: 2.0
  tmax: 6.0
